version: '3.9'
services:
  postgres-fastapi:
    image: postgres:latest
    container_name: postgres-fastapi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - postgres-fastapi
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - postgres-fastapi
    networks:
      - postgres-fastapi
networks:
  postgres-fastapi:
    driver: bridge